# Generated by Django 3.0.2 on 2020-01-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_delete_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='genre',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
