# Generated by Django 3.0.2 on 2020-01-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='process',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
