# Generated by Django 3.0.2 on 2020-01-30 21:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20200130_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ing1',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ing10',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ing11',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ing12',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ing13',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ing14',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ing15',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ing2',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ing3',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ing4',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ing5',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ing6',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ing7',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ing8',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ing9',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), null=True, size=None),
        ),
    ]
