# Generated by Django 3.0.2 on 2020-01-31 00:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20200130_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None),
        ),
    ]
